name: Repo Dispatch

on:
 pull_request:
    types:
      - closed
    branches:
      - main
    paths-ignore:
      - '.github/**'


jobs:
  trigger_sap:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test Case
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Branch name
        run: |
          echo "Branch name: ${{ github.ref }}"
      - name: Get repository info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Repository owner: ${{ github.repository_owner }}"  
          echo "Token is: ${{ github.token }}" 
          echo "comment is: ${{ github.event.head_commit.message }}"
