name: Create issue on commit 
on: 
  push: 
    paths: 
      - 'test/**' 
jobs: 
  create_issue: 
    runs-on: ubuntu-18.04 
    steps: 
      - name: Create issue using REST API 
        run: echo 'Hello'
